@startuml
skinparam dpi 300

actor Employee
actor User
actor Customer
left to right direction
rectangle {
    (Manage customer) as managecust
    (Browse purchase orders) as browsepo
    (Manage book catalog) as manageitem
    (Manage book inventory) as manageinvent
    (Manage book top rated) as managetoprated
}
rectangle {
    (Find book) as   finditem
    (Create an account) as createacc
    (Browse catalog) as browsecat
}
rectangle {
    (Create purchase order) as createpo
    (Login & logout) as logg
    (Update account) as updateacc
    (Buy books) as buyitem
}

User -> createacc
User -> browsecat
User -> finditem

Customer -> browsecat
Customer -> logg
Customer -> updateacc
Customer -> buyitem

Employee -> manageinvent
Employee -> managetoprated
Employee -> manageitem
Employee -> managecust
Employee -> browsepo

@enduml
